# MongoDB configuration file

# Network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0

# Storage
storage:
  dbPath: /data/db
  journal:
    enabled: true

# Security
security:
  authorization: enabled

# System log
systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true
